### PR TITLE
fix jwks setting thru

### LINKED ISSUE #1299: JWKS updater - not revoking keys correctly
### TL;DR

Keys that are no longer in the upstream publish attempt to revoke, but the DB isn't showing updates.

investigate + fix

/assign

### PR DESCRIPTION
**Pull request by mikehelmick**
Fixes #1299

## Proposed Changes

* Fix pointer issue, HealthAuthorityKey.Revoke wasn't updating the struct
* Move jwks from pkg to internal
* Add  health authority key purge
* increase test coverage

**Release Note**

```release-note
Thru date on health authority keys will be set correctly when they are synced from JWKS sources.
```

### CODE REVIEW

File: internal/verification/database/health_authority_db.go [hunk 1]
```diff
@@ -245,6 +245,26 @@ func (db *HealthAuthorityDB) AddHealthAuthorityKey(ctx context.Context, ha *mode
 	})
 }
 
+func (db *HealthAuthorityDB) PurgeHealthAuthorityKeys(ctx context.Context, ha *model.HealthAuthority, purgeBefore time.Time) (int64, error) {
+	purgeCount := int64(0)
+	err := db.db.InTx(ctx, pgx.Serializable, func(tx pgx.Tx) error {
+		result, err := tx.Exec(ctx, `
+			DELETE FROM HealthAuthorityKey
+			WHERE
+				health_authority_id = $1 AND (thru_timestamp IS NOT NULL and thru_timestamp < $2)
```
Comment (sethvargo) [inline internal/verification/database/health_authority_db.go:254]:
```suggestion
				health_authority_id = $1 AND (thru_timestamp IS NOT NULL AND thru_timestamp < $2)
```

**Review by sethvargo — APPROVED** [review]
/lgtm
